# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClueLess_QTGameboard.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClueGameBoard(object):
    def setupUi(self, ClueGameBoard):
        ClueGameBoard.setObjectName("ClueGameBoard")
        ClueGameBoard.resize(1261, 949)
        ClueGameBoard.setMinimumSize(QtCore.QSize(900, 700))
        ClueGameBoard.setMaximumSize(QtCore.QSize(1464, 949))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        ClueGameBoard.setFont(font)
        ClueGameBoard.setAcceptDrops(False)
        ClueGameBoard.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.gridLayout_2 = QtWidgets.QGridLayout(ClueGameBoard)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.left_side_layout = QtWidgets.QGroupBox(ClueGameBoard)
        self.left_side_layout.setMinimumSize(QtCore.QSize(200, 450))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.left_side_layout.setFont(font)
        self.left_side_layout.setStyleSheet("color: rgb(198, 198, 198);")
        self.left_side_layout.setObjectName("left_side_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_side_layout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_text_display_box = QtWidgets.QLabel(self.left_side_layout)
        self.chat_text_display_box.setAutoFillBackground(False)
        self.chat_text_display_box.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.chat_text_display_box.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.chat_text_display_box.setWordWrap(True)
        self.chat_text_display_box.setIndent(2)
        self.chat_text_display_box.setObjectName("chat_text_display_box")
        self.verticalLayout.addWidget(self.chat_text_display_box)
        self.message_input_text_box = QtWidgets.QTextEdit(self.left_side_layout)
        self.message_input_text_box.setMaximumSize(QtCore.QSize(16777215, 30))
        self.message_input_text_box.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.message_input_text_box.setInputMethodHints(QtCore.Qt.ImhNone)
        self.message_input_text_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.message_input_text_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.message_input_text_box.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.message_input_text_box.setObjectName("message_input_text_box")
        self.verticalLayout.addWidget(self.message_input_text_box)
        self.send_message_button = QtWidgets.QPushButton(self.left_side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_message_button.sizePolicy().hasHeightForWidth())
        self.send_message_button.setSizePolicy(sizePolicy)
        self.send_message_button.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.send_message_button.setFont(font)
        self.send_message_button.setStyleSheet("color: rgb(203, 203, 203);")
        self.send_message_button.setObjectName("send_message_button")
        self.verticalLayout.addWidget(self.send_message_button)
        self.quit_game_button = QtWidgets.QPushButton(self.left_side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_game_button.sizePolicy().hasHeightForWidth())
        self.quit_game_button.setSizePolicy(sizePolicy)
        self.quit_game_button.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.quit_game_button.setFont(font)
        self.quit_game_button.setStyleSheet("color: rgb(179, 179, 179);")
        self.quit_game_button.setObjectName("quit_game_button")
        self.verticalLayout.addWidget(self.quit_game_button)
        self.gridLayout_2.addWidget(self.left_side_layout, 0, 0, 3, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbNotebook = QtWidgets.QWidget(ClueGameBoard)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.gbNotebook.setFont(font)
        self.gbNotebook.setStyleSheet("color: rgb(216, 216, 216);")
        self.gbNotebook.setObjectName("gbNotebook")
        self.chkMissScarlet = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMissScarlet.setGeometry(QtCore.QRect(40, 30, 101, 20))
        self.chkMissScarlet.setChecked(False)
        self.chkMissScarlet.setObjectName("chkMissScarlet")
        self.chkColMustard = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkColMustard.setGeometry(QtCore.QRect(40, 60, 101, 20))
        self.chkColMustard.setObjectName("chkColMustard")
        self.chkMrsWhite = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMrsWhite.setGeometry(QtCore.QRect(40, 90, 101, 20))
        self.chkMrsWhite.setObjectName("chkMrsWhite")
        self.chkMrGreen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMrGreen.setGeometry(QtCore.QRect(40, 120, 101, 20))
        self.chkMrGreen.setObjectName("chkMrGreen")
        self.chkMrsPeacock = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMrsPeacock.setGeometry(QtCore.QRect(40, 150, 101, 20))
        self.chkMrsPeacock.setObjectName("chkMrsPeacock")
        self.chkProfPlum = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkProfPlum.setGeometry(QtCore.QRect(40, 180, 101, 20))
        self.chkProfPlum.setObjectName("chkProfPlum")
        self.chkRevolver = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkRevolver.setGeometry(QtCore.QRect(40, 330, 101, 20))
        self.chkRevolver.setObjectName("chkRevolver")
        self.chkCandlestick = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkCandlestick.setGeometry(QtCore.QRect(40, 240, 101, 20))
        self.chkCandlestick.setChecked(False)
        self.chkCandlestick.setObjectName("chkCandlestick")
        self.chkLeadPipe = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkLeadPipe.setGeometry(QtCore.QRect(40, 300, 101, 20))
        self.chkLeadPipe.setObjectName("chkLeadPipe")
        self.chkWrench = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkWrench.setGeometry(QtCore.QRect(40, 390, 101, 20))
        self.chkWrench.setObjectName("chkWrench")
        self.chkRope = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkRope.setGeometry(QtCore.QRect(40, 360, 101, 20))
        self.chkRope.setObjectName("chkRope")
        self.chkKnife = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkKnife.setGeometry(QtCore.QRect(40, 270, 101, 20))
        self.chkKnife.setObjectName("chkKnife")
        self.chkLibrary = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkLibrary.setGeometry(QtCore.QRect(40, 600, 101, 20))
        self.chkLibrary.setObjectName("chkLibrary")
        self.chkConservatory = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkConservatory.setGeometry(QtCore.QRect(40, 570, 101, 20))
        self.chkConservatory.setObjectName("chkConservatory")
        self.chkLounge = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkLounge.setGeometry(QtCore.QRect(40, 450, 101, 20))
        self.chkLounge.setChecked(False)
        self.chkLounge.setObjectName("chkLounge")
        self.chkDiningRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkDiningRoom.setGeometry(QtCore.QRect(40, 480, 101, 20))
        self.chkDiningRoom.setObjectName("chkDiningRoom")
        self.chkKitchen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkKitchen.setGeometry(QtCore.QRect(40, 510, 101, 20))
        self.chkKitchen.setObjectName("chkKitchen")
        self.chkBallroom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkBallroom.setGeometry(QtCore.QRect(40, 540, 101, 20))
        self.chkBallroom.setObjectName("chkBallroom")
        self.chkHall = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkHall.setGeometry(QtCore.QRect(40, 660, 101, 20))
        self.chkHall.setObjectName("chkHall")
        self.chkStudy = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkStudy.setGeometry(QtCore.QRect(40, 630, 101, 20))
        self.chkStudy.setObjectName("chkStudy")
        self.chkBilliardRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkBilliardRoom.setGeometry(QtCore.QRect(40, 690, 101, 20))
        self.chkBilliardRoom.setObjectName("chkBilliardRoom")
        self.chkSuggestStudy = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestStudy.setGeometry(QtCore.QRect(150, 630, 30, 20))
        self.chkSuggestStudy.setText("")
        self.chkSuggestStudy.setObjectName("chkSuggestStudy")
        self.chkSuggestDiningRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestDiningRoom.setGeometry(QtCore.QRect(150, 480, 30, 20))
        self.chkSuggestDiningRoom.setText("")
        self.chkSuggestDiningRoom.setObjectName("chkSuggestDiningRoom")
        self.chkSuggestLibrary = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestLibrary.setGeometry(QtCore.QRect(150, 600, 30, 20))
        self.chkSuggestLibrary.setText("")
        self.chkSuggestLibrary.setObjectName("chkSuggestLibrary")
        self.chkSuggestProfPlum = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestProfPlum.setGeometry(QtCore.QRect(150, 180, 30, 20))
        self.chkSuggestProfPlum.setText("")
        self.chkSuggestProfPlum.setObjectName("chkSuggestProfPlum")
        self.chkSuggestBilliardRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestBilliardRoom.setGeometry(QtCore.QRect(150, 690, 30, 20))
        self.chkSuggestBilliardRoom.setText("")
        self.chkSuggestBilliardRoom.setObjectName("chkSuggestBilliardRoom")
        self.chkSuggestRevolver = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestRevolver.setGeometry(QtCore.QRect(150, 330, 30, 20))
        self.chkSuggestRevolver.setText("")
        self.chkSuggestRevolver.setObjectName("chkSuggestRevolver")
        self.chkSuggestMissScarlet = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMissScarlet.setGeometry(QtCore.QRect(150, 30, 30, 20))
        self.chkSuggestMissScarlet.setText("")
        self.chkSuggestMissScarlet.setChecked(False)
        self.chkSuggestMissScarlet.setObjectName("chkSuggestMissScarlet")
        self.chkSuggestKitchen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestKitchen.setGeometry(QtCore.QRect(150, 510, 30, 20))
        self.chkSuggestKitchen.setText("")
        self.chkSuggestKitchen.setObjectName("chkSuggestKitchen")
        self.chkSuggestMrsPeacock = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMrsPeacock.setGeometry(QtCore.QRect(150, 150, 30, 20))
        self.chkSuggestMrsPeacock.setText("")
        self.chkSuggestMrsPeacock.setObjectName("chkSuggestMrsPeacock")
        self.chkSuggestMrGreen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMrGreen.setGeometry(QtCore.QRect(150, 120, 30, 20))
        self.chkSuggestMrGreen.setText("")
        self.chkSuggestMrGreen.setObjectName("chkSuggestMrGreen")
        self.chkSuggestHall = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestHall.setGeometry(QtCore.QRect(150, 660, 30, 20))
        self.chkSuggestHall.setText("")
        self.chkSuggestHall.setObjectName("chkSuggestHall")
        self.chkSuggestWrench = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestWrench.setGeometry(QtCore.QRect(150, 390, 30, 20))
        self.chkSuggestWrench.setText("")
        self.chkSuggestWrench.setObjectName("chkSuggestWrench")
        self.chkSuggestBallroom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestBallroom.setGeometry(QtCore.QRect(150, 540, 30, 20))
        self.chkSuggestBallroom.setText("")
        self.chkSuggestBallroom.setObjectName("chkSuggestBallroom")
        self.chkSuggestConservatory = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestConservatory.setGeometry(QtCore.QRect(150, 570, 30, 20))
        self.chkSuggestConservatory.setText("")
        self.chkSuggestConservatory.setObjectName("chkSuggestConservatory")
        self.chkSuggestMrsWhite = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMrsWhite.setGeometry(QtCore.QRect(150, 90, 30, 20))
        self.chkSuggestMrsWhite.setText("")
        self.chkSuggestMrsWhite.setObjectName("chkSuggestMrsWhite")
        self.chkSuggestKnife = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestKnife.setGeometry(QtCore.QRect(150, 270, 30, 20))
        self.chkSuggestKnife.setText("")
        self.chkSuggestKnife.setObjectName("chkSuggestKnife")
        self.chkSuggestLounge = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestLounge.setGeometry(QtCore.QRect(150, 450, 30, 20))
        self.chkSuggestLounge.setText("")
        self.chkSuggestLounge.setChecked(False)
        self.chkSuggestLounge.setObjectName("chkSuggestLounge")
        self.chkSuggestRope = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestRope.setGeometry(QtCore.QRect(150, 360, 30, 20))
        self.chkSuggestRope.setText("")
        self.chkSuggestRope.setObjectName("chkSuggestRope")
        self.chkSuggestCandlestick = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestCandlestick.setGeometry(QtCore.QRect(150, 240, 30, 20))
        self.chkSuggestCandlestick.setText("")
        self.chkSuggestCandlestick.setChecked(False)
        self.chkSuggestCandlestick.setObjectName("chkSuggestCandlestick")
        self.chkSuggestColMustard = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestColMustard.setGeometry(QtCore.QRect(150, 60, 30, 20))
        self.chkSuggestColMustard.setText("")
        self.chkSuggestColMustard.setObjectName("chkSuggestColMustard")
        self.chkSuggestLeadPipe = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestLeadPipe.setGeometry(QtCore.QRect(150, 300, 30, 20))
        self.chkSuggestLeadPipe.setText("")
        self.chkSuggestLeadPipe.setObjectName("chkSuggestLeadPipe")
        self.verticalLayout_2.addWidget(self.gbNotebook)
        self.make_move_button = QtWidgets.QPushButton(ClueGameBoard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.make_move_button.sizePolicy().hasHeightForWidth())
        self.make_move_button.setSizePolicy(sizePolicy)
        self.make_move_button.setMinimumSize(QtCore.QSize(0, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(198, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.make_move_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.make_move_button.setFont(font)
        self.make_move_button.setObjectName("make_move_button")
        self.verticalLayout_2.addWidget(self.make_move_button)
        self.make_suggestion_button = QtWidgets.QPushButton(ClueGameBoard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.make_suggestion_button.sizePolicy().hasHeightForWidth())
        self.make_suggestion_button.setSizePolicy(sizePolicy)
        self.make_suggestion_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.make_suggestion_button.setFont(font)
        self.make_suggestion_button.setStyleSheet("color: rgb(198, 198, 198);")
        self.make_suggestion_button.setObjectName("make_suggestion_button")
        self.verticalLayout_2.addWidget(self.make_suggestion_button)
        self.make_accusation_button = QtWidgets.QPushButton(ClueGameBoard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.make_accusation_button.sizePolicy().hasHeightForWidth())
        self.make_accusation_button.setSizePolicy(sizePolicy)
        self.make_accusation_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.make_accusation_button.setFont(font)
        self.make_accusation_button.setStyleSheet("color: rgb(198, 198, 198);")
        self.make_accusation_button.setObjectName("make_accusation_button")
        self.verticalLayout_2.addWidget(self.make_accusation_button)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 3, 1)
        self.game_status_window = QtWidgets.QLabel(ClueGameBoard)
        self.game_status_window.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.game_status_window.setFont(font)
        self.game_status_window.setAutoFillBackground(False)
        self.game_status_window.setStyleSheet("background-color: rgb(156, 156, 156);\n"
"border: 1px solid black;")
        self.game_status_window.setIndent(2)
        self.game_status_window.setObjectName("game_status_window")
        self.gridLayout_2.addWidget(self.game_status_window, 1, 1, 1, 1)
        self.card_holder_hlayout = QtWidgets.QWidget(ClueGameBoard)
        self.card_holder_hlayout.setObjectName("card_holder_hlayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.card_holder_hlayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.card_1 = QtWidgets.QLabel(self.card_holder_hlayout)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.card_1.setFont(font)
        self.card_1.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.card_1.setTextFormat(QtCore.Qt.AutoText)
        self.card_1.setAlignment(QtCore.Qt.AlignCenter)
        self.card_1.setObjectName("card_1")
        self.horizontalLayout.addWidget(self.card_1)
        self.card_2 = QtWidgets.QLabel(self.card_holder_hlayout)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.card_2.setFont(font)
        self.card_2.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.card_2.setAlignment(QtCore.Qt.AlignCenter)
        self.card_2.setObjectName("card_2")
        self.horizontalLayout.addWidget(self.card_2)
        self.card_3 = QtWidgets.QLabel(self.card_holder_hlayout)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.card_3.setFont(font)
        self.card_3.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.card_3.setAlignment(QtCore.Qt.AlignCenter)
        self.card_3.setObjectName("card_3")
        self.horizontalLayout.addWidget(self.card_3)
        self.card_4 = QtWidgets.QLabel(self.card_holder_hlayout)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.card_4.setFont(font)
        self.card_4.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.card_4.setAlignment(QtCore.Qt.AlignCenter)
        self.card_4.setObjectName("card_4")
        self.horizontalLayout.addWidget(self.card_4)
        self.card_5 = QtWidgets.QLabel(self.card_holder_hlayout)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.card_5.setFont(font)
        self.card_5.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.card_5.setAlignment(QtCore.Qt.AlignCenter)
        self.card_5.setObjectName("card_5")
        self.horizontalLayout.addWidget(self.card_5)
        self.card_6 = QtWidgets.QLabel(self.card_holder_hlayout)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.card_6.setFont(font)
        self.card_6.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.card_6.setAlignment(QtCore.Qt.AlignCenter)
        self.card_6.setObjectName("card_6")
        self.horizontalLayout.addWidget(self.card_6)
        self.gridLayout_2.addWidget(self.card_holder_hlayout, 2, 1, 1, 1)
        self.gbGameboard = QtWidgets.QGroupBox(ClueGameBoard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGameboard.sizePolicy().hasHeightForWidth())
        self.gbGameboard.setSizePolicy(sizePolicy)
        self.gbGameboard.setMinimumSize(QtCore.QSize(0, 700))
        self.gbGameboard.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.gbGameboard.setFont(font)
        self.gbGameboard.setAcceptDrops(True)
        self.gbGameboard.setStyleSheet("color: rgb(186, 186, 186);")
        self.gbGameboard.setObjectName("gbGameboard")
        self.suspectMrsPeacock = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMrsPeacock.setGeometry(QtCore.QRect(280, 90, 51, 41))
        self.suspectMrsPeacock.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMrsPeacock.setText("")
        self.suspectMrsPeacock.setPixmap(QtGui.QPixmap("Assets/blue_game_piece.png"))
        self.suspectMrsPeacock.setScaledContents(True)
        self.suspectMrsPeacock.setObjectName("suspectMrsPeacock")
        self.suspectMissScarlet = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMissScarlet.setGeometry(QtCore.QRect(560, 90, 51, 41))
        self.suspectMissScarlet.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMissScarlet.setText("")
        self.suspectMissScarlet.setPixmap(QtGui.QPixmap("Assets/red_game_piece.png"))
        self.suspectMissScarlet.setScaledContents(True)
        self.suspectMissScarlet.setObjectName("suspectMissScarlet")
        self.suspectProfPlum = QtWidgets.QLabel(self.gbGameboard)
        self.suspectProfPlum.setGeometry(QtCore.QRect(280, 570, 51, 41))
        self.suspectProfPlum.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectProfPlum.setText("")
        self.suspectProfPlum.setPixmap(QtGui.QPixmap("Assets/purple_game_piece.png"))
        self.suspectProfPlum.setScaledContents(True)
        self.suspectProfPlum.setObjectName("suspectProfPlum")
        self.suspectColMustard = QtWidgets.QLabel(self.gbGameboard)
        self.suspectColMustard.setGeometry(QtCore.QRect(560, 570, 51, 41))
        self.suspectColMustard.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectColMustard.setText("")
        self.suspectColMustard.setPixmap(QtGui.QPixmap("Assets/yellow_game_piece.png"))
        self.suspectColMustard.setScaledContents(True)
        self.suspectColMustard.setObjectName("suspectColMustard")
        self.weaponCandleStick = QtWidgets.QLabel(self.gbGameboard)
        self.weaponCandleStick.setGeometry(QtCore.QRect(80, 610, 61, 51))
        self.weaponCandleStick.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponCandleStick.setText("")
        self.weaponCandleStick.setPixmap(QtGui.QPixmap("Assets/candlestick_game_piece.png"))
        self.weaponCandleStick.setScaledContents(True)
        self.weaponCandleStick.setObjectName("weaponCandleStick")
        self.weaponKnife = QtWidgets.QLabel(self.gbGameboard)
        self.weaponKnife.setGeometry(QtCore.QRect(400, 610, 61, 51))
        self.weaponKnife.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponKnife.setText("")
        self.weaponKnife.setPixmap(QtGui.QPixmap("Assets/knife_game_piece.png"))
        self.weaponKnife.setScaledContents(True)
        self.weaponKnife.setObjectName("weaponKnife")
        self.weaponLeadPipe = QtWidgets.QLabel(self.gbGameboard)
        self.weaponLeadPipe.setGeometry(QtCore.QRect(760, 620, 51, 41))
        self.weaponLeadPipe.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponLeadPipe.setText("")
        self.weaponLeadPipe.setPixmap(QtGui.QPixmap("Assets/lead_pipe_game_piece.png"))
        self.weaponLeadPipe.setScaledContents(True)
        self.weaponLeadPipe.setObjectName("weaponLeadPipe")
        self.weaponRope = QtWidgets.QLabel(self.gbGameboard)
        self.weaponRope.setGeometry(QtCore.QRect(770, 130, 41, 51))
        self.weaponRope.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponRope.setText("")
        self.weaponRope.setPixmap(QtGui.QPixmap("Assets/rope_game_piece.png"))
        self.weaponRope.setScaledContents(True)
        self.weaponRope.setObjectName("weaponRope")
        self.weaponRevolver = QtWidgets.QLabel(self.gbGameboard)
        self.weaponRevolver.setGeometry(QtCore.QRect(420, 150, 51, 31))
        self.weaponRevolver.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponRevolver.setText("")
        self.weaponRevolver.setPixmap(QtGui.QPixmap("Assets/revolver_game_piece.png"))
        self.weaponRevolver.setScaledContents(True)
        self.weaponRevolver.setObjectName("weaponRevolver")
        self.weaponWrench = QtWidgets.QLabel(self.gbGameboard)
        self.weaponWrench.setGeometry(QtCore.QRect(80, 150, 61, 31))
        self.weaponWrench.setAcceptDrops(True)
        self.weaponWrench.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponWrench.setText("")
        self.weaponWrench.setPixmap(QtGui.QPixmap("Assets/wrench_game_piece.png"))
        self.weaponWrench.setScaledContents(True)
        self.weaponWrench.setObjectName("weaponWrench")
        self.suspectMrGreen = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMrGreen.setGeometry(QtCore.QRect(140, 450, 51, 41))
        self.suspectMrGreen.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMrGreen.setText("")
        self.suspectMrGreen.setPixmap(QtGui.QPixmap("Assets/green_game_piece.png"))
        self.suspectMrGreen.setScaledContents(True)
        self.suspectMrGreen.setObjectName("suspectMrGreen")
        self.suspectMrsWhite = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMrsWhite.setGeometry(QtCore.QRect(700, 210, 51, 41))
        self.suspectMrsWhite.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMrsWhite.setText("")
        self.suspectMrsWhite.setPixmap(QtGui.QPixmap("Assets/orange_game_piece.png"))
        self.suspectMrsWhite.setScaledContents(True)
        self.suspectMrsWhite.setObjectName("suspectMrsWhite")
        self.groupBox = QtWidgets.QGroupBox(self.gbGameboard)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 511, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.roomHall = QtWidgets.QLabel(self.groupBox)
        self.roomHall.setMinimumSize(QtCore.QSize(0, 122))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomHall.setFont(font)
        self.roomHall.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomHall.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.roomHall.setIndent(2)
        self.roomHall.setObjectName("roomHall")
        self.gridLayout.addWidget(self.roomHall, 0, 2, 1, 1)
        self.hall5_2 = QtWidgets.QLabel(self.groupBox)
        self.hall5_2.setMinimumSize(QtCore.QSize(0, 122))
        self.hall5_2.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall5_2.setText("")
        self.hall5_2.setObjectName("hall5_2")
        self.gridLayout.addWidget(self.hall5_2, 4, 1, 1, 1)
        self.hall5_4 = QtWidgets.QLabel(self.groupBox)
        self.hall5_4.setMinimumSize(QtCore.QSize(0, 122))
        self.hall5_4.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall5_4.setText("")
        self.hall5_4.setObjectName("hall5_4")
        self.gridLayout.addWidget(self.hall5_4, 4, 3, 1, 1)
        self.roomBallroom = QtWidgets.QLabel(self.groupBox)
        self.roomBallroom.setMinimumSize(QtCore.QSize(0, 122))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomBallroom.setFont(font)
        self.roomBallroom.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomBallroom.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.roomBallroom.setIndent(2)
        self.roomBallroom.setObjectName("roomBallroom")
        self.gridLayout.addWidget(self.roomBallroom, 4, 2, 1, 1)
        self.roomKitchen = QtWidgets.QLabel(self.groupBox)
        self.roomKitchen.setMinimumSize(QtCore.QSize(0, 122))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomKitchen.setFont(font)
        self.roomKitchen.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomKitchen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.roomKitchen.setIndent(2)
        self.roomKitchen.setObjectName("roomKitchen")
        self.gridLayout.addWidget(self.roomKitchen, 4, 4, 1, 1)
        self.hall1_2 = QtWidgets.QLabel(self.groupBox)
        self.hall1_2.setMinimumSize(QtCore.QSize(0, 0))
        self.hall1_2.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall1_2.setText("")
        self.hall1_2.setObjectName("hall1_2")
        self.gridLayout.addWidget(self.hall1_2, 0, 1, 1, 1)
        self.hall3_4 = QtWidgets.QLabel(self.groupBox)
        self.hall3_4.setMinimumSize(QtCore.QSize(0, 123))
        self.hall3_4.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall3_4.setText("")
        self.hall3_4.setObjectName("hall3_4")
        self.gridLayout.addWidget(self.hall3_4, 2, 3, 1, 1)
        self.hall2_5 = QtWidgets.QLabel(self.groupBox)
        self.hall2_5.setMinimumSize(QtCore.QSize(0, 122))
        self.hall2_5.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall2_5.setText("")
        self.hall2_5.setObjectName("hall2_5")
        self.gridLayout.addWidget(self.hall2_5, 1, 4, 1, 1)
        self.hall4_3 = QtWidgets.QLabel(self.groupBox)
        self.hall4_3.setMinimumSize(QtCore.QSize(0, 122))
        self.hall4_3.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall4_3.setText("")
        self.hall4_3.setObjectName("hall4_3")
        self.gridLayout.addWidget(self.hall4_3, 3, 2, 1, 1)
        self.hall4_1 = QtWidgets.QLabel(self.groupBox)
        self.hall4_1.setMinimumSize(QtCore.QSize(0, 122))
        self.hall4_1.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall4_1.setText("")
        self.hall4_1.setObjectName("hall4_1")
        self.gridLayout.addWidget(self.hall4_1, 3, 0, 1, 1)
        self.roomDiningRoom = QtWidgets.QLabel(self.groupBox)
        self.roomDiningRoom.setMinimumSize(QtCore.QSize(0, 123))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomDiningRoom.setFont(font)
        self.roomDiningRoom.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomDiningRoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.roomDiningRoom.setIndent(2)
        self.roomDiningRoom.setObjectName("roomDiningRoom")
        self.gridLayout.addWidget(self.roomDiningRoom, 2, 4, 1, 1)
        self.hall2_1 = QtWidgets.QLabel(self.groupBox)
        self.hall2_1.setMinimumSize(QtCore.QSize(0, 122))
        self.hall2_1.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall2_1.setText("")
        self.hall2_1.setObjectName("hall2_1")
        self.gridLayout.addWidget(self.hall2_1, 1, 0, 1, 1)
        self.hall2_3 = QtWidgets.QLabel(self.groupBox)
        self.hall2_3.setMinimumSize(QtCore.QSize(0, 122))
        self.hall2_3.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall2_3.setText("")
        self.hall2_3.setObjectName("hall2_3")
        self.gridLayout.addWidget(self.hall2_3, 1, 2, 1, 1)
        self.roomLounge = QtWidgets.QLabel(self.groupBox)
        self.roomLounge.setMinimumSize(QtCore.QSize(0, 122))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomLounge.setFont(font)
        self.roomLounge.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomLounge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.roomLounge.setIndent(2)
        self.roomLounge.setObjectName("roomLounge")
        self.gridLayout.addWidget(self.roomLounge, 0, 4, 1, 1)
        self.hall4_5 = QtWidgets.QLabel(self.groupBox)
        self.hall4_5.setMinimumSize(QtCore.QSize(0, 122))
        self.hall4_5.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall4_5.setText("")
        self.hall4_5.setObjectName("hall4_5")
        self.gridLayout.addWidget(self.hall4_5, 3, 4, 1, 1)
        self.roomConservatory = QtWidgets.QLabel(self.groupBox)
        self.roomConservatory.setMinimumSize(QtCore.QSize(0, 122))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomConservatory.setFont(font)
        self.roomConservatory.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomConservatory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.roomConservatory.setIndent(2)
        self.roomConservatory.setObjectName("roomConservatory")
        self.gridLayout.addWidget(self.roomConservatory, 4, 0, 1, 1)
        self.hall1_4 = QtWidgets.QLabel(self.groupBox)
        self.hall1_4.setMinimumSize(QtCore.QSize(0, 122))
        self.hall1_4.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall1_4.setText("")
        self.hall1_4.setObjectName("hall1_4")
        self.gridLayout.addWidget(self.hall1_4, 0, 3, 1, 1)
        self.hall3_2 = QtWidgets.QLabel(self.groupBox)
        self.hall3_2.setMinimumSize(QtCore.QSize(0, 123))
        self.hall3_2.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall3_2.setText("")
        self.hall3_2.setObjectName("hall3_2")
        self.gridLayout.addWidget(self.hall3_2, 2, 1, 1, 1)
        self.roomLibrary = QtWidgets.QLabel(self.groupBox)
        self.roomLibrary.setMinimumSize(QtCore.QSize(0, 123))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomLibrary.setFont(font)
        self.roomLibrary.setStyleSheet("background-color: rgb(170, 85, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomLibrary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.roomLibrary.setIndent(2)
        self.roomLibrary.setObjectName("roomLibrary")
        self.gridLayout.addWidget(self.roomLibrary, 2, 0, 1, 1)
        self.roomBilliardRoom = QtWidgets.QLabel(self.groupBox)
        self.roomBilliardRoom.setMinimumSize(QtCore.QSize(0, 123))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomBilliardRoom.setFont(font)
        self.roomBilliardRoom.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomBilliardRoom.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.roomBilliardRoom.setIndent(2)
        self.roomBilliardRoom.setObjectName("roomBilliardRoom")
        self.gridLayout.addWidget(self.roomBilliardRoom, 2, 2, 1, 1)
        self.roomStudy = QtWidgets.QLabel(self.groupBox)
        self.roomStudy.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomStudy.setFont(font)
        self.roomStudy.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomStudy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.roomStudy.setIndent(0)
        self.roomStudy.setObjectName("roomStudy")
        self.gridLayout.addWidget(self.roomStudy, 0, 0, 1, 1)
        self.groupBox.raise_()
        self.suspectMrsPeacock.raise_()
        self.suspectMissScarlet.raise_()
        self.suspectProfPlum.raise_()
        self.suspectColMustard.raise_()
        self.weaponCandleStick.raise_()
        self.weaponKnife.raise_()
        self.weaponLeadPipe.raise_()
        self.weaponRope.raise_()
        self.weaponRevolver.raise_()
        self.weaponWrench.raise_()
        self.suspectMrGreen.raise_()
        self.suspectMrsWhite.raise_()
        self.gridLayout_2.addWidget(self.gbGameboard, 0, 1, 1, 1)
        self.hall5_2.setBuddy(self.groupBox)

        self.retranslateUi(ClueGameBoard)
        QtCore.QMetaObject.connectSlotsByName(ClueGameBoard)

    def retranslateUi(self, ClueGameBoard):
        _translate = QtCore.QCoreApplication.translate
        ClueGameBoard.setWindowTitle(_translate("ClueGameBoard", "ClueLess by Team Laeviculus"))
        self.left_side_layout.setTitle(_translate("ClueGameBoard", "Messages"))
        self.chat_text_display_box.setText(_translate("ClueGameBoard", "Greetings !!!....Welcome to ClueLess"))
        self.send_message_button.setText(_translate("ClueGameBoard", "Send"))
        self.quit_game_button.setText(_translate("ClueGameBoard", "Quit Game"))
        self.chkMissScarlet.setText(_translate("ClueGameBoard", "Miss Scarlet"))
        self.chkColMustard.setText(_translate("ClueGameBoard", "Col Mustard"))
        self.chkMrsWhite.setText(_translate("ClueGameBoard", "Mrs. White"))
        self.chkMrGreen.setText(_translate("ClueGameBoard", "Mr. Green"))
        self.chkMrsPeacock.setText(_translate("ClueGameBoard", "Mrs. Peacock"))
        self.chkProfPlum.setText(_translate("ClueGameBoard", "Prof. Plum"))
        self.chkRevolver.setText(_translate("ClueGameBoard", "Revolver"))
        self.chkCandlestick.setText(_translate("ClueGameBoard", "Candlestick"))
        self.chkLeadPipe.setText(_translate("ClueGameBoard", "Lead Pipe"))
        self.chkWrench.setText(_translate("ClueGameBoard", "Wrench"))
        self.chkRope.setText(_translate("ClueGameBoard", "Rope"))
        self.chkKnife.setText(_translate("ClueGameBoard", "Knife"))
        self.chkLibrary.setText(_translate("ClueGameBoard", "Library"))
        self.chkConservatory.setText(_translate("ClueGameBoard", "Conservatory"))
        self.chkLounge.setText(_translate("ClueGameBoard", "Lounge"))
        self.chkDiningRoom.setText(_translate("ClueGameBoard", "Dining Room"))
        self.chkKitchen.setText(_translate("ClueGameBoard", "Kitchen"))
        self.chkBallroom.setText(_translate("ClueGameBoard", "Ballroom"))
        self.chkHall.setText(_translate("ClueGameBoard", "Hall"))
        self.chkStudy.setText(_translate("ClueGameBoard", "Study"))
        self.chkBilliardRoom.setText(_translate("ClueGameBoard", "Billiard Room"))
        self.make_move_button.setText(_translate("ClueGameBoard", "Move"))
        self.make_suggestion_button.setText(_translate("ClueGameBoard", "Make Suggestion"))
        self.make_accusation_button.setText(_translate("ClueGameBoard", "Make Accusation"))
        self.game_status_window.setText(_translate("ClueGameBoard", "Waiting for game..."))
        self.card_1.setText(_translate("ClueGameBoard", "Col Mustard"))
        self.card_2.setText(_translate("ClueGameBoard", "Prof Plum"))
        self.card_3.setText(_translate("ClueGameBoard", "Lead Pipe"))
        self.card_4.setText(_translate("ClueGameBoard", "Revolver"))
        self.card_5.setText(_translate("ClueGameBoard", "Library"))
        self.card_6.setText(_translate("ClueGameBoard", "Study"))
        self.gbGameboard.setTitle(_translate("ClueGameBoard", "Gameboard"))
        self.roomHall.setText(_translate("ClueGameBoard", "Hall"))
        self.roomBallroom.setText(_translate("ClueGameBoard", "Ballroom"))
        self.roomKitchen.setText(_translate("ClueGameBoard", "Kitchen"))
        self.roomDiningRoom.setText(_translate("ClueGameBoard", "Dining Room"))
        self.roomLounge.setText(_translate("ClueGameBoard", "Lounge"))
        self.roomConservatory.setText(_translate("ClueGameBoard", "Conservatory"))
        self.roomLibrary.setText(_translate("ClueGameBoard", "Library"))
        self.roomBilliardRoom.setText(_translate("ClueGameBoard", "Billiard Room"))
        self.roomStudy.setText(_translate("ClueGameBoard", "Study"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClueGameBoard = QtWidgets.QDialog()
    ui = Ui_ClueGameBoard()
    ui.setupUi(ClueGameBoard)
    ClueGameBoard.show()
    sys.exit(app.exec_())

