# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClueLess_Gameboard_Prototype.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1464, 949)
        Dialog.setMinimumSize(QtCore.QSize(1464, 949))
        Dialog.setMaximumSize(QtCore.QSize(1464, 949))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(False)
        Dialog.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.butSuggestion = QtWidgets.QPushButton(Dialog)
        self.butSuggestion.setGeometry(QtCore.QRect(1200, 860, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.butSuggestion.setFont(font)
        self.butSuggestion.setStyleSheet("color: rgb(198, 198, 198);")
        self.butSuggestion.setObjectName("butSuggestion")
        self.butAccusation = QtWidgets.QPushButton(Dialog)
        self.butAccusation.setGeometry(QtCore.QRect(1330, 860, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.butAccusation.setFont(font)
        self.butAccusation.setStyleSheet("color: rgb(198, 198, 198);")
        self.butAccusation.setObjectName("butAccusation")
        self.butQuit = QtWidgets.QPushButton(Dialog)
        self.butQuit.setGeometry(QtCore.QRect(40, 870, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.butQuit.setFont(font)
        self.butQuit.setStyleSheet("color: rgb(179, 179, 179);")
        self.butQuit.setObjectName("butQuit")
        self.gbNotebook = QtWidgets.QGroupBox(Dialog)
        self.gbNotebook.setGeometry(QtCore.QRect(1210, 20, 211, 731))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.gbNotebook.setFont(font)
        self.gbNotebook.setStyleSheet("color: rgb(216, 216, 216);")
        self.gbNotebook.setObjectName("gbNotebook")
        self.chkMissScarlet = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMissScarlet.setGeometry(QtCore.QRect(40, 30, 101, 20))
        self.chkMissScarlet.setChecked(False)
        self.chkMissScarlet.setObjectName("chkMissScarlet")
        self.chkColMustard = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkColMustard.setGeometry(QtCore.QRect(40, 60, 101, 20))
        self.chkColMustard.setObjectName("chkColMustard")
        self.chkMrsWhite = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMrsWhite.setGeometry(QtCore.QRect(40, 90, 101, 20))
        self.chkMrsWhite.setObjectName("chkMrsWhite")
        self.chkMrGreen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMrGreen.setGeometry(QtCore.QRect(40, 120, 101, 20))
        self.chkMrGreen.setObjectName("chkMrGreen")
        self.chkMrsPeacock = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkMrsPeacock.setGeometry(QtCore.QRect(40, 150, 101, 20))
        self.chkMrsPeacock.setObjectName("chkMrsPeacock")
        self.chkProfPlum = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkProfPlum.setGeometry(QtCore.QRect(40, 180, 101, 20))
        self.chkProfPlum.setObjectName("chkProfPlum")
        self.chkRevolver = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkRevolver.setGeometry(QtCore.QRect(40, 330, 101, 20))
        self.chkRevolver.setObjectName("chkRevolver")
        self.chkCandlestick = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkCandlestick.setGeometry(QtCore.QRect(40, 240, 101, 20))
        self.chkCandlestick.setChecked(False)
        self.chkCandlestick.setObjectName("chkCandlestick")
        self.chkLeadPipe = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkLeadPipe.setGeometry(QtCore.QRect(40, 300, 101, 20))
        self.chkLeadPipe.setObjectName("chkLeadPipe")
        self.chkWrench = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkWrench.setGeometry(QtCore.QRect(40, 390, 101, 20))
        self.chkWrench.setObjectName("chkWrench")
        self.chkRope = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkRope.setGeometry(QtCore.QRect(40, 360, 101, 20))
        self.chkRope.setObjectName("chkRope")
        self.chkKnife = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkKnife.setGeometry(QtCore.QRect(40, 270, 101, 20))
        self.chkKnife.setObjectName("chkKnife")
        self.chkLibrary = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkLibrary.setGeometry(QtCore.QRect(40, 600, 101, 20))
        self.chkLibrary.setObjectName("chkLibrary")
        self.chkConservatory = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkConservatory.setGeometry(QtCore.QRect(40, 570, 101, 20))
        self.chkConservatory.setObjectName("chkConservatory")
        self.chkLounge = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkLounge.setGeometry(QtCore.QRect(40, 450, 101, 20))
        self.chkLounge.setChecked(False)
        self.chkLounge.setObjectName("chkLounge")
        self.chkDiningRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkDiningRoom.setGeometry(QtCore.QRect(40, 480, 101, 20))
        self.chkDiningRoom.setObjectName("chkDiningRoom")
        self.chkKitchen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkKitchen.setGeometry(QtCore.QRect(40, 510, 101, 20))
        self.chkKitchen.setObjectName("chkKitchen")
        self.chkBallroom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkBallroom.setGeometry(QtCore.QRect(40, 540, 101, 20))
        self.chkBallroom.setObjectName("chkBallroom")
        self.chkHall = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkHall.setGeometry(QtCore.QRect(40, 660, 101, 20))
        self.chkHall.setObjectName("chkHall")
        self.chkStudy = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkStudy.setGeometry(QtCore.QRect(40, 630, 101, 20))
        self.chkStudy.setObjectName("chkStudy")
        self.chkBilliardRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkBilliardRoom.setGeometry(QtCore.QRect(40, 690, 101, 20))
        self.chkBilliardRoom.setObjectName("chkBilliardRoom")
        self.chkSuggestStudy = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestStudy.setGeometry(QtCore.QRect(150, 630, 30, 20))
        self.chkSuggestStudy.setText("")
        self.chkSuggestStudy.setObjectName("chkSuggestStudy")
        self.chkSuggestDiningRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestDiningRoom.setGeometry(QtCore.QRect(150, 480, 30, 20))
        self.chkSuggestDiningRoom.setText("")
        self.chkSuggestDiningRoom.setObjectName("chkSuggestDiningRoom")
        self.chkSuggestLibrary = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestLibrary.setGeometry(QtCore.QRect(150, 600, 30, 20))
        self.chkSuggestLibrary.setText("")
        self.chkSuggestLibrary.setObjectName("chkSuggestLibrary")
        self.chkSuggestProfPlum = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestProfPlum.setGeometry(QtCore.QRect(150, 180, 30, 20))
        self.chkSuggestProfPlum.setText("")
        self.chkSuggestProfPlum.setObjectName("chkSuggestProfPlum")
        self.chkSuggestBilliardRoom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestBilliardRoom.setGeometry(QtCore.QRect(150, 690, 30, 20))
        self.chkSuggestBilliardRoom.setText("")
        self.chkSuggestBilliardRoom.setObjectName("chkSuggestBilliardRoom")
        self.chkSuggestRevolver = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestRevolver.setGeometry(QtCore.QRect(150, 330, 30, 20))
        self.chkSuggestRevolver.setText("")
        self.chkSuggestRevolver.setObjectName("chkSuggestRevolver")
        self.chkSuggestMissScarlet = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMissScarlet.setGeometry(QtCore.QRect(150, 30, 30, 20))
        self.chkSuggestMissScarlet.setText("")
        self.chkSuggestMissScarlet.setChecked(False)
        self.chkSuggestMissScarlet.setObjectName("chkSuggestMissScarlet")
        self.chkSuggestKitchen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestKitchen.setGeometry(QtCore.QRect(150, 510, 30, 20))
        self.chkSuggestKitchen.setText("")
        self.chkSuggestKitchen.setObjectName("chkSuggestKitchen")
        self.chkSuggestMrsPeacock = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMrsPeacock.setGeometry(QtCore.QRect(150, 150, 30, 20))
        self.chkSuggestMrsPeacock.setText("")
        self.chkSuggestMrsPeacock.setObjectName("chkSuggestMrsPeacock")
        self.chkSuggestMrGreen = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMrGreen.setGeometry(QtCore.QRect(150, 120, 30, 20))
        self.chkSuggestMrGreen.setText("")
        self.chkSuggestMrGreen.setObjectName("chkSuggestMrGreen")
        self.chkSuggestHall = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestHall.setGeometry(QtCore.QRect(150, 660, 30, 20))
        self.chkSuggestHall.setText("")
        self.chkSuggestHall.setObjectName("chkSuggestHall")
        self.chkSuggestWrench = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestWrench.setGeometry(QtCore.QRect(150, 390, 30, 20))
        self.chkSuggestWrench.setText("")
        self.chkSuggestWrench.setObjectName("chkSuggestWrench")
        self.chkSuggestBallroom = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestBallroom.setGeometry(QtCore.QRect(150, 540, 30, 20))
        self.chkSuggestBallroom.setText("")
        self.chkSuggestBallroom.setObjectName("chkSuggestBallroom")
        self.chkSuggestConservatory = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestConservatory.setGeometry(QtCore.QRect(150, 570, 30, 20))
        self.chkSuggestConservatory.setText("")
        self.chkSuggestConservatory.setObjectName("chkSuggestConservatory")
        self.chkSuggestMrsWhite = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestMrsWhite.setGeometry(QtCore.QRect(150, 90, 30, 20))
        self.chkSuggestMrsWhite.setText("")
        self.chkSuggestMrsWhite.setObjectName("chkSuggestMrsWhite")
        self.chkSuggestKnife = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestKnife.setGeometry(QtCore.QRect(150, 270, 30, 20))
        self.chkSuggestKnife.setText("")
        self.chkSuggestKnife.setObjectName("chkSuggestKnife")
        self.chkSuggestLounge = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestLounge.setGeometry(QtCore.QRect(150, 450, 30, 20))
        self.chkSuggestLounge.setText("")
        self.chkSuggestLounge.setChecked(False)
        self.chkSuggestLounge.setObjectName("chkSuggestLounge")
        self.chkSuggestRope = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestRope.setGeometry(QtCore.QRect(150, 360, 30, 20))
        self.chkSuggestRope.setText("")
        self.chkSuggestRope.setObjectName("chkSuggestRope")
        self.chkSuggestCandlestick = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestCandlestick.setGeometry(QtCore.QRect(150, 240, 30, 20))
        self.chkSuggestCandlestick.setText("")
        self.chkSuggestCandlestick.setChecked(False)
        self.chkSuggestCandlestick.setObjectName("chkSuggestCandlestick")
        self.chkSuggestColMustard = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestColMustard.setGeometry(QtCore.QRect(150, 60, 30, 20))
        self.chkSuggestColMustard.setText("")
        self.chkSuggestColMustard.setObjectName("chkSuggestColMustard")
        self.chkSuggestLeadPipe = QtWidgets.QCheckBox(self.gbNotebook)
        self.chkSuggestLeadPipe.setGeometry(QtCore.QRect(150, 300, 30, 20))
        self.chkSuggestLeadPipe.setText("")
        self.chkSuggestLeadPipe.setObjectName("chkSuggestLeadPipe")
        self.gbGameboard = QtWidgets.QGroupBox(Dialog)
        self.gbGameboard.setGeometry(QtCore.QRect(300, 20, 881, 691))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.gbGameboard.setFont(font)
        self.gbGameboard.setAcceptDrops(True)
        self.gbGameboard.setStyleSheet("color: rgb(186, 186, 186);")
        self.gbGameboard.setObjectName("gbGameboard")
        self.roomStudy = QtWidgets.QLabel(self.gbGameboard)
        self.roomStudy.setGeometry(QtCore.QRect(70, 30, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomStudy.setFont(font)
        self.roomStudy.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomStudy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.roomStudy.setIndent(2)
        self.roomStudy.setObjectName("roomStudy")
        self.roomHall = QtWidgets.QLabel(self.gbGameboard)
        self.roomHall.setGeometry(QtCore.QRect(350, 30, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomHall.setFont(font)
        self.roomHall.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomHall.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.roomHall.setIndent(2)
        self.roomHall.setObjectName("roomHall")
        self.roomLounge = QtWidgets.QLabel(self.gbGameboard)
        self.roomLounge.setGeometry(QtCore.QRect(630, 30, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomLounge.setFont(font)
        self.roomLounge.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomLounge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.roomLounge.setIndent(2)
        self.roomLounge.setObjectName("roomLounge")
        self.roomDiningRoom = QtWidgets.QLabel(self.gbGameboard)
        self.roomDiningRoom.setGeometry(QtCore.QRect(630, 270, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomDiningRoom.setFont(font)
        self.roomDiningRoom.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomDiningRoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.roomDiningRoom.setIndent(2)
        self.roomDiningRoom.setObjectName("roomDiningRoom")
        self.roomLibrary = QtWidgets.QLabel(self.gbGameboard)
        self.roomLibrary.setGeometry(QtCore.QRect(70, 270, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomLibrary.setFont(font)
        self.roomLibrary.setStyleSheet("background-color: rgb(170, 85, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomLibrary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.roomLibrary.setIndent(2)
        self.roomLibrary.setObjectName("roomLibrary")
        self.roomBilliardRoom = QtWidgets.QLabel(self.gbGameboard)
        self.roomBilliardRoom.setGeometry(QtCore.QRect(350, 270, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomBilliardRoom.setFont(font)
        self.roomBilliardRoom.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomBilliardRoom.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.roomBilliardRoom.setIndent(2)
        self.roomBilliardRoom.setObjectName("roomBilliardRoom")
        self.roomKitchen = QtWidgets.QLabel(self.gbGameboard)
        self.roomKitchen.setGeometry(QtCore.QRect(630, 510, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomKitchen.setFont(font)
        self.roomKitchen.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomKitchen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.roomKitchen.setIndent(2)
        self.roomKitchen.setObjectName("roomKitchen")
        self.roomConservatory = QtWidgets.QLabel(self.gbGameboard)
        self.roomConservatory.setGeometry(QtCore.QRect(70, 510, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomConservatory.setFont(font)
        self.roomConservatory.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomConservatory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.roomConservatory.setIndent(2)
        self.roomConservatory.setObjectName("roomConservatory")
        self.roomBallroom = QtWidgets.QLabel(self.gbGameboard)
        self.roomBallroom.setGeometry(QtCore.QRect(350, 510, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.roomBallroom.setFont(font)
        self.roomBallroom.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.roomBallroom.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.roomBallroom.setIndent(2)
        self.roomBallroom.setObjectName("roomBallroom")
        self.hall1_2 = QtWidgets.QLabel(self.gbGameboard)
        self.hall1_2.setGeometry(QtCore.QRect(260, 70, 91, 81))
        self.hall1_2.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall1_2.setText("")
        self.hall1_2.setObjectName("hall1_2")
        self.hall1_4 = QtWidgets.QLabel(self.gbGameboard)
        self.hall1_4.setGeometry(QtCore.QRect(540, 70, 91, 81))
        self.hall1_4.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall1_4.setText("")
        self.hall1_4.setObjectName("hall1_4")
        self.hall3_2 = QtWidgets.QLabel(self.gbGameboard)
        self.hall3_2.setGeometry(QtCore.QRect(260, 310, 91, 81))
        self.hall3_2.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall3_2.setText("")
        self.hall3_2.setObjectName("hall3_2")
        self.hall3_4 = QtWidgets.QLabel(self.gbGameboard)
        self.hall3_4.setGeometry(QtCore.QRect(540, 310, 91, 81))
        self.hall3_4.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall3_4.setText("")
        self.hall3_4.setObjectName("hall3_4")
        self.hall5_2 = QtWidgets.QLabel(self.gbGameboard)
        self.hall5_2.setGeometry(QtCore.QRect(260, 550, 91, 81))
        self.hall5_2.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall5_2.setText("")
        self.hall5_2.setObjectName("hall5_2")
        self.hall5_4 = QtWidgets.QLabel(self.gbGameboard)
        self.hall5_4.setGeometry(QtCore.QRect(540, 550, 91, 81))
        self.hall5_4.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall5_4.setText("")
        self.hall5_4.setObjectName("hall5_4")
        self.hall4_1 = QtWidgets.QLabel(self.gbGameboard)
        self.hall4_1.setGeometry(QtCore.QRect(120, 430, 91, 81))
        self.hall4_1.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall4_1.setText("")
        self.hall4_1.setObjectName("hall4_1")
        self.hall2_1 = QtWidgets.QLabel(self.gbGameboard)
        self.hall2_1.setGeometry(QtCore.QRect(120, 190, 91, 81))
        self.hall2_1.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall2_1.setText("")
        self.hall2_1.setObjectName("hall2_1")
        self.hall2_3 = QtWidgets.QLabel(self.gbGameboard)
        self.hall2_3.setGeometry(QtCore.QRect(400, 190, 91, 81))
        self.hall2_3.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall2_3.setText("")
        self.hall2_3.setObjectName("hall2_3")
        self.hall4_3 = QtWidgets.QLabel(self.gbGameboard)
        self.hall4_3.setGeometry(QtCore.QRect(400, 430, 91, 81))
        self.hall4_3.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall4_3.setText("")
        self.hall4_3.setObjectName("hall4_3")
        self.hall2_5 = QtWidgets.QLabel(self.gbGameboard)
        self.hall2_5.setGeometry(QtCore.QRect(680, 190, 91, 81))
        self.hall2_5.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall2_5.setText("")
        self.hall2_5.setObjectName("hall2_5")
        self.hall4_5 = QtWidgets.QLabel(self.gbGameboard)
        self.hall4_5.setGeometry(QtCore.QRect(680, 430, 91, 81))
        self.hall4_5.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.hall4_5.setText("")
        self.hall4_5.setObjectName("hall4_5")
        self.suspectMrsPeacock = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMrsPeacock.setGeometry(QtCore.QRect(280, 90, 51, 41))
        self.suspectMrsPeacock.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMrsPeacock.setText("")
        self.suspectMrsPeacock.setPixmap(QtGui.QPixmap("blue_game_piece.png"))
        self.suspectMrsPeacock.setScaledContents(True)
        self.suspectMrsPeacock.setObjectName("suspectMrsPeacock")
        self.suspectMissScarlet = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMissScarlet.setGeometry(QtCore.QRect(560, 90, 51, 41))
        self.suspectMissScarlet.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMissScarlet.setText("")
        self.suspectMissScarlet.setPixmap(QtGui.QPixmap("red_game_piece.png"))
        self.suspectMissScarlet.setScaledContents(True)
        self.suspectMissScarlet.setObjectName("suspectMissScarlet")
        self.suspectProfPlum = QtWidgets.QLabel(self.gbGameboard)
        self.suspectProfPlum.setGeometry(QtCore.QRect(280, 570, 51, 41))
        self.suspectProfPlum.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectProfPlum.setText("")
        self.suspectProfPlum.setPixmap(QtGui.QPixmap("purple_game_piece.png"))
        self.suspectProfPlum.setScaledContents(True)
        self.suspectProfPlum.setObjectName("suspectProfPlum")
        self.suspectColMustard = QtWidgets.QLabel(self.gbGameboard)
        self.suspectColMustard.setGeometry(QtCore.QRect(560, 570, 51, 41))
        self.suspectColMustard.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectColMustard.setText("")
        self.suspectColMustard.setPixmap(QtGui.QPixmap("yellow_game_piece.png"))
        self.suspectColMustard.setScaledContents(True)
        self.suspectColMustard.setObjectName("suspectColMustard")
        self.weaponCandleStick = QtWidgets.QLabel(self.gbGameboard)
        self.weaponCandleStick.setGeometry(QtCore.QRect(80, 610, 61, 51))
        self.weaponCandleStick.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponCandleStick.setText("")
        self.weaponCandleStick.setPixmap(QtGui.QPixmap("candlestick_game_piece.png"))
        self.weaponCandleStick.setScaledContents(True)
        self.weaponCandleStick.setObjectName("weaponCandleStick")
        self.weaponKnife = QtWidgets.QLabel(self.gbGameboard)
        self.weaponKnife.setGeometry(QtCore.QRect(400, 610, 61, 51))
        self.weaponKnife.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponKnife.setText("")
        self.weaponKnife.setPixmap(QtGui.QPixmap("knife_game_piece.png"))
        self.weaponKnife.setScaledContents(True)
        self.weaponKnife.setObjectName("weaponKnife")
        self.weaponLeadPipe = QtWidgets.QLabel(self.gbGameboard)
        self.weaponLeadPipe.setGeometry(QtCore.QRect(760, 620, 51, 41))
        self.weaponLeadPipe.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponLeadPipe.setText("")
        self.weaponLeadPipe.setPixmap(QtGui.QPixmap("lead_pipe_game_piece.png"))
        self.weaponLeadPipe.setScaledContents(True)
        self.weaponLeadPipe.setObjectName("weaponLeadPipe")
        self.weaponRope = QtWidgets.QLabel(self.gbGameboard)
        self.weaponRope.setGeometry(QtCore.QRect(770, 130, 41, 51))
        self.weaponRope.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponRope.setText("")
        self.weaponRope.setPixmap(QtGui.QPixmap("rope_game_piece.png"))
        self.weaponRope.setScaledContents(True)
        self.weaponRope.setObjectName("weaponRope")
        self.weaponRevolver = QtWidgets.QLabel(self.gbGameboard)
        self.weaponRevolver.setGeometry(QtCore.QRect(420, 150, 51, 31))
        self.weaponRevolver.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponRevolver.setText("")
        self.weaponRevolver.setPixmap(QtGui.QPixmap("revolver_game_piece.png"))
        self.weaponRevolver.setScaledContents(True)
        self.weaponRevolver.setObjectName("weaponRevolver")
        self.weaponWrench = QtWidgets.QLabel(self.gbGameboard)
        self.weaponWrench.setGeometry(QtCore.QRect(80, 150, 61, 31))
        self.weaponWrench.setAcceptDrops(True)
        self.weaponWrench.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.weaponWrench.setText("")
        self.weaponWrench.setPixmap(QtGui.QPixmap("wrench_game_piece.png"))
        self.weaponWrench.setScaledContents(True)
        self.weaponWrench.setObjectName("weaponWrench")
        self.suspectMrGreen = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMrGreen.setGeometry(QtCore.QRect(140, 450, 51, 41))
        self.suspectMrGreen.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMrGreen.setText("")
        self.suspectMrGreen.setPixmap(QtGui.QPixmap("green_game_piece.png"))
        self.suspectMrGreen.setScaledContents(True)
        self.suspectMrGreen.setObjectName("suspectMrGreen")
        self.suspectMrsWhite = QtWidgets.QLabel(self.gbGameboard)
        self.suspectMrsWhite.setGeometry(QtCore.QRect(700, 210, 51, 41))
        self.suspectMrsWhite.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.suspectMrsWhite.setText("")
        self.suspectMrsWhite.setPixmap(QtGui.QPixmap("orange_game_piece.png"))
        self.suspectMrsWhite.setScaledContents(True)
        self.suspectMrsWhite.setObjectName("suspectMrsWhite")
        self.hall4_5.raise_()
        self.hall2_5.raise_()
        self.hall2_3.raise_()
        self.hall4_3.raise_()
        self.hall4_1.raise_()
        self.hall2_1.raise_()
        self.hall5_4.raise_()
        self.hall5_2.raise_()
        self.hall3_4.raise_()
        self.hall3_2.raise_()
        self.hall1_4.raise_()
        self.hall1_2.raise_()
        self.roomStudy.raise_()
        self.roomHall.raise_()
        self.roomLounge.raise_()
        self.roomDiningRoom.raise_()
        self.roomLibrary.raise_()
        self.roomBilliardRoom.raise_()
        self.roomKitchen.raise_()
        self.roomConservatory.raise_()
        self.roomBallroom.raise_()
        self.suspectMrsPeacock.raise_()
        self.suspectMissScarlet.raise_()
        self.suspectProfPlum.raise_()
        self.suspectColMustard.raise_()
        self.weaponCandleStick.raise_()
        self.weaponKnife.raise_()
        self.weaponLeadPipe.raise_()
        self.weaponRope.raise_()
        self.weaponRevolver.raise_()
        self.weaponWrench.raise_()
        self.suspectMrGreen.raise_()
        self.suspectMrsWhite.raise_()
        self.lblStatusMessage = QtWidgets.QLabel(Dialog)
        self.lblStatusMessage.setGeometry(QtCore.QRect(350, 720, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblStatusMessage.setFont(font)
        self.lblStatusMessage.setAutoFillBackground(False)
        self.lblStatusMessage.setStyleSheet("background-color: rgb(156, 156, 156);\n"
"border: 1px solid black;")
        self.lblStatusMessage.setIndent(2)
        self.lblStatusMessage.setObjectName("lblStatusMessage")
        self.gbMessages = QtWidgets.QGroupBox(Dialog)
        self.gbMessages.setGeometry(QtCore.QRect(30, 20, 251, 731))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.gbMessages.setFont(font)
        self.gbMessages.setStyleSheet("color: rgb(198, 198, 198);")
        self.gbMessages.setObjectName("gbMessages")
        self.lstMessages = QtWidgets.QLabel(self.gbMessages)
        self.lstMessages.setGeometry(QtCore.QRect(10, 30, 231, 691))
        self.lstMessages.setAutoFillBackground(False)
        self.lstMessages.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lstMessages.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lstMessages.setIndent(2)
        self.lstMessages.setObjectName("lstMessages")
        self.txtSendMessage = QtWidgets.QTextEdit(Dialog)
        self.txtSendMessage.setGeometry(QtCore.QRect(30, 760, 251, 31))
        self.txtSendMessage.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.txtSendMessage.setObjectName("txtSendMessage")
        self.butSend = QtWidgets.QPushButton(Dialog)
        self.butSend.setGeometry(QtCore.QRect(30, 800, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.butSend.setFont(font)
        self.butSend.setStyleSheet("color: rgb(203, 203, 203);")
        self.butSend.setObjectName("butSend")
        self.pCard1 = QtWidgets.QLabel(Dialog)
        self.pCard1.setGeometry(QtCore.QRect(300, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.pCard1.setFont(font)
        self.pCard1.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.pCard1.setTextFormat(QtCore.Qt.AutoText)
        self.pCard1.setAlignment(QtCore.Qt.AlignCenter)
        self.pCard1.setObjectName("pCard1")
        self.pCard2 = QtWidgets.QLabel(Dialog)
        self.pCard2.setGeometry(QtCore.QRect(450, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.pCard2.setFont(font)
        self.pCard2.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.pCard2.setAlignment(QtCore.Qt.AlignCenter)
        self.pCard2.setObjectName("pCard2")
        self.pCard3 = QtWidgets.QLabel(Dialog)
        self.pCard3.setGeometry(QtCore.QRect(600, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.pCard3.setFont(font)
        self.pCard3.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.pCard3.setAlignment(QtCore.Qt.AlignCenter)
        self.pCard3.setObjectName("pCard3")
        self.pCard4 = QtWidgets.QLabel(Dialog)
        self.pCard4.setGeometry(QtCore.QRect(750, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.pCard4.setFont(font)
        self.pCard4.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.pCard4.setAlignment(QtCore.Qt.AlignCenter)
        self.pCard4.setObjectName("pCard4")
        self.pCard5 = QtWidgets.QLabel(Dialog)
        self.pCard5.setGeometry(QtCore.QRect(900, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.pCard5.setFont(font)
        self.pCard5.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.pCard5.setAlignment(QtCore.Qt.AlignCenter)
        self.pCard5.setObjectName("pCard5")
        self.pCard6 = QtWidgets.QLabel(Dialog)
        self.pCard6.setGeometry(QtCore.QRect(1050, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.pCard6.setFont(font)
        self.pCard6.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.pCard6.setAlignment(QtCore.Qt.AlignCenter)
        self.pCard6.setObjectName("pCard6")
        self.lblStatusIndicator = QtWidgets.QLabel(Dialog)
        self.lblStatusIndicator.setGeometry(QtCore.QRect(300, 720, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblStatusIndicator.setFont(font)
        self.lblStatusIndicator.setAutoFillBackground(False)
        self.lblStatusIndicator.setStyleSheet("background-color: rgb(156, 156, 156);\n"
"border: 1px solid black;")
        self.lblStatusIndicator.setText("")
        self.lblStatusIndicator.setIndent(2)
        self.lblStatusIndicator.setObjectName("lblStatusIndicator")
        self.butMove = QtWidgets.QPushButton(Dialog)
        self.butMove.setGeometry(QtCore.QRect(1200, 790, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.butMove.setFont(font)
        self.butMove.setStyleSheet("color: rgb(198, 198, 198);")
        self.butMove.setObjectName("butMove")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ClueLess by Team Laeviculus"))
        self.butSuggestion.setText(_translate("Dialog", "Suggestion"))
        self.butAccusation.setText(_translate("Dialog", "Accusation"))
        self.butQuit.setText(_translate("Dialog", "Quit Game"))
        self.gbNotebook.setTitle(_translate("Dialog", "Notebook"))
        self.chkMissScarlet.setText(_translate("Dialog", "Miss Scarlet"))
        self.chkColMustard.setText(_translate("Dialog", "Col Mustard"))
        self.chkMrsWhite.setText(_translate("Dialog", "Mrs. White"))
        self.chkMrGreen.setText(_translate("Dialog", "Mr. Green"))
        self.chkMrsPeacock.setText(_translate("Dialog", "Mrs. Peacock"))
        self.chkProfPlum.setText(_translate("Dialog", "Prof. Plum"))
        self.chkRevolver.setText(_translate("Dialog", "Revolver"))
        self.chkCandlestick.setText(_translate("Dialog", "Candlestick"))
        self.chkLeadPipe.setText(_translate("Dialog", "Lead Pipe"))
        self.chkWrench.setText(_translate("Dialog", "Wrench"))
        self.chkRope.setText(_translate("Dialog", "Rope"))
        self.chkKnife.setText(_translate("Dialog", "Knife"))
        self.chkLibrary.setText(_translate("Dialog", "Library"))
        self.chkConservatory.setText(_translate("Dialog", "Conservatory"))
        self.chkLounge.setText(_translate("Dialog", "Lounge"))
        self.chkDiningRoom.setText(_translate("Dialog", "Dining Room"))
        self.chkKitchen.setText(_translate("Dialog", "Kitchen"))
        self.chkBallroom.setText(_translate("Dialog", "Ballroom"))
        self.chkHall.setText(_translate("Dialog", "Hall"))
        self.chkStudy.setText(_translate("Dialog", "Study"))
        self.chkBilliardRoom.setText(_translate("Dialog", "Billiard Room"))
        self.gbGameboard.setTitle(_translate("Dialog", "Gameboard"))
        self.roomStudy.setText(_translate("Dialog", "Study"))
        self.roomHall.setText(_translate("Dialog", "Hall"))
        self.roomLounge.setText(_translate("Dialog", "Lounge"))
        self.roomDiningRoom.setText(_translate("Dialog", "Dining Room"))
        self.roomLibrary.setText(_translate("Dialog", "Library"))
        self.roomBilliardRoom.setText(_translate("Dialog", "Billiard Room"))
        self.roomKitchen.setText(_translate("Dialog", "Kitchen"))
        self.roomConservatory.setText(_translate("Dialog", "Conservatory"))
        self.roomBallroom.setText(_translate("Dialog", "Ballroom"))
        self.lblStatusMessage.setText(_translate("Dialog", "Waiting for game..."))
        self.gbMessages.setTitle(_translate("Dialog", "Messages"))
        self.lstMessages.setText(_translate("Dialog", "Greetings !!!....Welcome to ClueLess"))
        self.butSend.setText(_translate("Dialog", "Send"))
        self.pCard1.setText(_translate("Dialog", "Mrs. Peacock"))
        self.pCard2.setText(_translate("Dialog", "Prof Plum"))
        self.pCard3.setText(_translate("Dialog", "Lead Pipe"))
        self.pCard4.setText(_translate("Dialog", "Revolver"))
        self.pCard5.setText(_translate("Dialog", "Library"))
        self.pCard6.setText(_translate("Dialog", "Conservatory"))
        self.butMove.setText(_translate("Dialog", "Move"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

