# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClueLess_Gameboard_Prototype.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
ASSETS_PATH = "Assets/"

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1464, 949)
        Dialog.setMinimumSize(QtCore.QSize(1464, 949))
        Dialog.setMaximumSize(QtCore.QSize(1464, 949))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(False)
        Dialog.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1210, 790, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(198, 198, 198);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(1210, 860, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(198, 198, 198);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 870, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(179, 179, 179);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(1210, 20, 211, 731))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(216, 216, 216);")
        self.groupBox.setObjectName("groupBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 30, 121, 20))
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 60, 121, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(40, 90, 121, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(40, 120, 121, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(40, 150, 121, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(40, 180, 121, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(40, 330, 121, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(40, 240, 121, 20))
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setGeometry(QtCore.QRect(40, 300, 121, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(40, 390, 121, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_12.setGeometry(QtCore.QRect(40, 360, 121, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_13.setGeometry(QtCore.QRect(40, 270, 121, 20))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_14.setGeometry(QtCore.QRect(40, 600, 121, 20))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_15.setGeometry(QtCore.QRect(40, 570, 121, 20))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_16.setGeometry(QtCore.QRect(40, 450, 121, 20))
        self.checkBox_16.setChecked(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_17.setGeometry(QtCore.QRect(40, 480, 121, 20))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_18.setGeometry(QtCore.QRect(40, 510, 121, 20))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_19.setGeometry(QtCore.QRect(40, 540, 121, 20))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_20.setGeometry(QtCore.QRect(40, 660, 121, 20))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_21.setGeometry(QtCore.QRect(40, 630, 121, 20))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_22.setGeometry(QtCore.QRect(40, 690, 121, 20))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_23.setGeometry(QtCore.QRect(140, 630, 30, 20))
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_24.setGeometry(QtCore.QRect(140, 480, 30, 20))
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_25.setGeometry(QtCore.QRect(140, 600, 30, 20))
        self.checkBox_25.setText("")
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_26.setGeometry(QtCore.QRect(140, 180, 30, 20))
        self.checkBox_26.setText("")
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_27.setGeometry(QtCore.QRect(140, 690, 30, 20))
        self.checkBox_27.setText("")
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_28.setGeometry(QtCore.QRect(140, 330, 30, 20))
        self.checkBox_28.setText("")
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_29.setGeometry(QtCore.QRect(140, 30, 30, 20))
        self.checkBox_29.setText("")
        self.checkBox_29.setChecked(False)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_30.setGeometry(QtCore.QRect(140, 510, 30, 20))
        self.checkBox_30.setText("")
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_31.setGeometry(QtCore.QRect(140, 150, 30, 20))
        self.checkBox_31.setText("")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_32.setGeometry(QtCore.QRect(140, 120, 30, 20))
        self.checkBox_32.setText("")
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_33.setGeometry(QtCore.QRect(140, 660, 30, 20))
        self.checkBox_33.setText("")
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_34.setGeometry(QtCore.QRect(140, 390, 30, 20))
        self.checkBox_34.setText("")
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_35.setGeometry(QtCore.QRect(140, 540, 30, 20))
        self.checkBox_35.setText("")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_36.setGeometry(QtCore.QRect(140, 570, 30, 20))
        self.checkBox_36.setText("")
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_37.setGeometry(QtCore.QRect(140, 90, 30, 20))
        self.checkBox_37.setText("")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_38.setGeometry(QtCore.QRect(140, 270, 30, 20))
        self.checkBox_38.setText("")
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_39.setGeometry(QtCore.QRect(140, 450, 30, 20))
        self.checkBox_39.setText("")
        self.checkBox_39.setChecked(False)
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_40.setGeometry(QtCore.QRect(140, 360, 30, 20))
        self.checkBox_40.setText("")
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_41.setGeometry(QtCore.QRect(140, 240, 30, 20))
        self.checkBox_41.setText("")
        self.checkBox_41.setChecked(False)
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_42.setGeometry(QtCore.QRect(140, 60, 30, 20))
        self.checkBox_42.setText("")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_43.setGeometry(QtCore.QRect(140, 300, 30, 20))
        self.checkBox_43.setText("")
        self.checkBox_43.setObjectName("checkBox_43")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 20, 881, 691))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAcceptDrops(True)
        self.groupBox_2.setStyleSheet("color: rgb(186, 186, 186);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setIndent(2)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setIndent(2)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(630, 30, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_6.setIndent(2)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(630, 270, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_7.setIndent(2)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(70, 270, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(170, 85, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setIndent(2)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(350, 270, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setIndent(2)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(630, 510, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_10.setIndent(2)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(70, 510, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setIndent(2)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(350, 510, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border: 1px solid black;\n"
"color: rgb(0, 0, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setIndent(2)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(260, 70, 91, 81))
        self.label_13.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(540, 70, 91, 81))
        self.label_14.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(260, 310, 91, 81))
        self.label_15.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(540, 310, 91, 81))
        self.label_16.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(260, 550, 91, 81))
        self.label_17.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(540, 550, 91, 81))
        self.label_18.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(120, 430, 91, 81))
        self.label_19.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(120, 190, 91, 81))
        self.label_20.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(400, 190, 91, 81))
        self.label_21.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(400, 430, 91, 81))
        self.label_22.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(680, 190, 91, 81))
        self.label_23.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(680, 430, 91, 81))
        self.label_24.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(280, 90, 51, 41))
        self.label_31.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap(ASSETS_PATH + "blue_game_piece.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_31.setAcceptDrops(True)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(560, 90, 51, 41))
        self.label_32.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(ASSETS_PATH + "red_game_piece.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(280, 570, 51, 41))
        self.label_33.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap(ASSETS_PATH + "purple_game_piece.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(560, 570, 51, 41))
        self.label_34.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap(ASSETS_PATH + "yellow_game_piece.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(80, 610, 61, 51))
        self.label_35.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap(ASSETS_PATH + "candlestick_game_piece.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(400, 610, 61, 51))
        self.label_36.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap(ASSETS_PATH + "knife_game_piece.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(760, 620, 51, 41))
        self.label_37.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap(ASSETS_PATH + "lead_pipe_game_piece.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(770, 130, 41, 51))
        self.label_38.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap(ASSETS_PATH + "rope_game_piece.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(420, 150, 51, 31))
        self.label_39.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap(ASSETS_PATH + "revolver_game_piece.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(80, 150, 61, 31))
        self.label_40.setAcceptDrops(True)
        self.label_40.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap(ASSETS_PATH + "wrench_game_piece.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(140, 450, 51, 41))
        self.label_41.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap(ASSETS_PATH + "green_game_piece.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(700, 210, 51, 41))
        self.label_42.setStyleSheet("background-color: rgba(0, 0, 0, 0%);")
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap(ASSETS_PATH + "orange_game_piece.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.label_24.raise_()
        self.label_23.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.label_15.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(350, 720, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(156, 156, 156);\n"
"border: 1px solid black;")
        self.label_2.setIndent(2)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 20, 251, 731))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color: rgb(198, 198, 198);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 231, 691))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setIndent(2)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 760, 251, 31))
        self.textEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 800, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(203, 203, 203);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(300, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(450, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(600, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(750, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(900, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(1050, 760, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid brown;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_43 = QtWidgets.QLabel(Dialog)
        self.label_43.setGeometry(QtCore.QRect(300, 720, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_43.setFont(font)
        self.label_43.setAutoFillBackground(False)
        self.label_43.setStyleSheet("background-color: rgb(156, 156, 156);\n"
"border: 1px solid black;")
        self.label_43.setText("")
        self.label_43.setIndent(2)
        self.label_43.setObjectName("label_43")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ClueLess by Team Laeviculus"))
        self.pushButton.setText(_translate("Dialog", "Make Suggestion"))
        self.pushButton_2.setText(_translate("Dialog", "Make Accusation"))
        self.pushButton_3.setText(_translate("Dialog", "Quit Game"))
        self.groupBox.setTitle(_translate("Dialog", "Player 1 Notebook"))
        self.checkBox_2.setText(_translate("Dialog", "Suspect 1"))
        self.checkBox_3.setText(_translate("Dialog", "Suspect 1"))
        self.checkBox_4.setText(_translate("Dialog", "Suspect 1"))
        self.checkBox_5.setText(_translate("Dialog", "Suspect 1"))
        self.checkBox_6.setText(_translate("Dialog", "Suspect 1"))
        self.checkBox_7.setText(_translate("Dialog", "Suspect 1"))
        self.checkBox_8.setText(_translate("Dialog", "Weapon 1"))
        self.checkBox_9.setText(_translate("Dialog", "Weapon 1"))
        self.checkBox_10.setText(_translate("Dialog", "Weapon 1"))
        self.checkBox_11.setText(_translate("Dialog", "Weapon 1"))
        self.checkBox_12.setText(_translate("Dialog", "Weapon 1"))
        self.checkBox_13.setText(_translate("Dialog", "Weapon 1"))
        self.checkBox_14.setText(_translate("Dialog", "Room 1"))
        self.checkBox_15.setText(_translate("Dialog", "Room 1"))
        self.checkBox_16.setText(_translate("Dialog", "Room 1"))
        self.checkBox_17.setText(_translate("Dialog", "Room 1"))
        self.checkBox_18.setText(_translate("Dialog", "Room 1"))
        self.checkBox_19.setText(_translate("Dialog", "Room 1"))
        self.checkBox_20.setText(_translate("Dialog", "Room 1"))
        self.checkBox_21.setText(_translate("Dialog", "Room 1"))
        self.checkBox_22.setText(_translate("Dialog", "Room 1"))
        self.groupBox_2.setTitle(_translate("Dialog", "Gameboard"))
        self.label_4.setText(_translate("Dialog", "Study"))
        self.label_5.setText(_translate("Dialog", "Hall"))
        self.label_6.setText(_translate("Dialog", "Lounge"))
        self.label_7.setText(_translate("Dialog", "Dining Room"))
        self.label_8.setText(_translate("Dialog", "Library"))
        self.label_9.setText(_translate("Dialog", "Billiard Room"))
        self.label_10.setText(_translate("Dialog", "Kitchen"))
        self.label_11.setText(_translate("Dialog", "Conservatory"))
        self.label_12.setText(_translate("Dialog", "Ballroom"))
        self.label_2.setText(_translate("Dialog", "Waiting for game..."))
        self.groupBox_3.setTitle(_translate("Dialog", "Messages"))
        self.label_3.setText(_translate("Dialog", "Greetings !!!....Welcome to ClueLess"))
        self.pushButton_5.setText(_translate("Dialog", "Send"))
        self.label_25.setText(_translate("Dialog", "Col Mustard"))
        self.label_26.setText(_translate("Dialog", "Prof Plum"))
        self.label_27.setText(_translate("Dialog", "Lead Pipe"))
        self.label_28.setText(_translate("Dialog", "Revolver"))
        self.label_29.setText(_translate("Dialog", "Library"))
        self.label_30.setText(_translate("Dialog", "Study"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

